### ISSUE TITLE
No files being Picked  up 

### ISSUE THREAD

**Issue by Julian-mostert** [seanap/auto-m4b#45]
Hey all hope someone can spread some light here,
I have set this up but can't get the files to merge.

I see that the auto-m4b-tool.log has this error
[auto-m4b-tool.log](setuser: user autom4b not found)

Here is my docker file
```YAML
version: '3.7'
services:
  auto-m4b:
    image: seanap/auto-m4b
    container_name: auto-m4b
    volumes:
      - G:\m4bMerge:/config
      - G:\temp:/temp
    environment:
      - PUID=0
      - PGID=0
      - CPU_CORES=2
      - SLEEPTIME=1m
      - MAKE_BACKUP=Y
```

here is my folder setup
![image](https://github.com/seanap/auto-m4b/assets/10965681/df450f97-9bc6-47da-841c-c667b19aef5f)
