### ISSUE TITLE
user for container is still taken as root even after specifying puid and pgid

### ISSUE THREAD

**Issue by hackmonker** [seanap/auto-m4b#46]
```
  auto-m4b:
    image: seanap/auto-m4b
    container_name: auto-m4b
    volumes:
      - /opt/containers/auto-m4b:/config
      - /mnt/local/Processing/Audiobooks:/temp
    environment:
      - PUID=1000
      - PGID=1000
      - CPU_CORES=2
      - SLEEPTIME=1m
      - MAKE_BACKUP=N
```

This is my config but the permissions for folders and /config is still root. is this intended behavior?  since it affects further movement of the files under the personal user which has puid and pgid as 1000
